spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrmex?createDatabaseIfNotExist=true&autoReconnect=true&showSSL=false
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 2025